on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@master
      - uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Build
        run: |
          echo 'demo' >> d.txt
          ls
          git add *
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          branch: '${{ github.ref }}'
