on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-node@v2.1.2
      - name: Build
        run: echo "demo" >> d
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.ref }}
