name: Render README.md

on: push

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git clone https://github.com/anxgit/anxgit.git
        cd anxgit
        rm -rf README.md
        cp ../README.md README.md
        git add .
        git commit -m "Update"
        git push
