name: Render README.md

on: push

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secret.GITHUB_TOKEN }}
    - run: |
        git clone https://github.com/anxgit/anxgit.git
        cd anxgit
        rm -rf README.md
        cp ../README.md README.md
        it config --global user.email "biz.showpozitif5@gmail.com"
        git config --global user.name "Alexander"
        git add .
        git commit -m "Update"
        git push
