name: Render README.md

on: push

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git clone https://github.com/anxgit/anxgit.git
        rm -rf anxgit/README.md
        cp README.md anxgit/README.md
